### PR TITLE
Use org.bukkit.Color instead of TextColor in Text Hologram Background

### PR DESCRIPTION
**Pull request by UsainSrht**
I'd recommend saving background field in only one way instead of `transparent`, `green`, `#RRGGBB`
If that's okay I can create another pr for that.

### CODE REVIEW

**Comment by OakLoaf** [comment]
Do you think you could rename this or move the persistent related commits into a separate branch/pr. After you've done that I can review the PR

**Comment by OakLoaf** [comment]
Just making note that this PR would resolve https://github.com/FancyMcPlugins/FancyHolograms/pull/33

**Comment by UsainSrht** [comment]
> Do you think you could rename this or move the persistent related commits into a separate branch/pr. After you've done that I can review the PR
Yeah I accidentally committed persistent holograms here too, I'll create two different branches for these two features.

**Comment by UsainSrht** [comment]
separated as #95 & #96

**Pull request closed without merging**
