### PR TITLE
Add hologram Converter API

### PR DESCRIPTION
**Pull request by Matt-MX**
Adds the `HologramConverter` interface for creating multiple converter implementations.
> e.g. a builtin `DecentHologramsConverter` that converts lines and optionally attempts to convert **icons** to item holograms that align with the text

Adds the `FHConversionRegistry` to store and procure all `HologramConverter`.
Adds the `/fancyholograms convert <converterId> <target> [args...]` command to invoke the converters.
Adds the `ConverterTarget` class which is essentially a regex to target holograms individually or as groups.

An example of API usage:

```java
ConverterTarget target = ConverterTarget.all();

// The constructor can also take in a CommandSender sender  and String[] args for logging results/errors and processing additional arguments.
HologramConversionSession session = new HologramConversionSession(target);

FHConversionRegistry.getConverterById("DecentHolograms")
  .ifPresent((converter) -> {
    List<HologramData> data = converter.convert(session);

    // Handle the data yourself e.g. add it to manager and save.
  });
```

### CODE REVIEW

**Comment by Matt-MX** [comment]
This additionally allows players to control `translation` of holograms through the command `/holo edit <hologram> translation <x> <y> <z>`

**Review by OliverSchlueter — COMMENTED** [review]
When I type "/fancyholograms convert DecentHolograms " and then press tab, it throws an exception "DecentHolograms holograms folder doesn't exist or is empty"
I probably wound't suggest DecentHolograms at all, when the folder is empty or doesn't exists.
There are a few TODO comments in the DecentHologramsConverter class, idk if you wanted to solve them.
LGTM otherwise

**Comment by Matt-MX** [comment]
I'll have a look at the exception and finish the TODOs, I think it's just for handling errors.

**Comment by Matt-MX** [comment]
@OliverSchlueter Should have fixed the thrown exception, also filters out any converters deemed not usable from tab completion.

**Review by OliverSchlueter — APPROVED** [review]

**Pull request merged**
